name = "Test_Project"
short_name = "sail-test"
author = "Cole Wilson"
email = ""
short_description = ""
description = ""
url = "https://github.com/cole-wilson/sail-test"
keywords = ""
latest_build = "1.0.0"
license = "MIT"

[resources]
icon = ""
data_files = []
modules = []
file = "main.py"
no_import = []

[build]
type = "1"
homebrew = true
mac = true
windows = true
installer = true
actions = true
bundle_id = "com.colewilson.sail_test"
actions_built_latest = false

[git]
github = "cole-wilson/sail-test"

[build.commands]
ctest = ""
