# v0.0.5, workflow subs: [name: `Test_Project`, short_name: `sail-test`, mac_comment: ``, windows_comment: ``, mac_extension: `.dmg`, windows_extension: `.exe`]
name: Publish release files for Test_Project.

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_path: ./dist/pypi/*.whl
            asset_name: sail-test-$tag-py3-none-any.whl
            glob: true
          - os: windows-latest
            artifact_path: .\dist\pyinstaller\Test_Project.exe
            asset_name: sail-test-$tag-windows64.exe
            glob: false
          - os: macos-latest
            artifact_path: ./Test_Project.dmg
            asset_name: sail-test-$tag-macos.dmg
            glob: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
    - name: Install Dependencies and Build
      run: |
        pip install sailboat
        python -m sailboat.actions
    - name: Check for prerelease
      run: python -m sailboat.prerelease ${{ github.ref }} >> $GITHUB_ENV
    - name: Upload binaries to prerelease
      if: env.prerel == 'true'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_path }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        file_glob: ${{ matrix.glob }}
        body: ${{ github.event.head_commit.message }}
        prerelease: true
      
    - name: Upload binaries to production release
      if: env.prerel != 'true'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_path }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        file_glob: ${{ matrix.glob }}
        body: ${{ github.event.head_commit.message }}
        prerelease: false